config/routes.rb
Rails.application.routes.draw do
  root 'stepper#index'
  get 'stepper/index'
  get 'stepper/one'
  get 'stepper/two'
  get 'stepper/three'
  post 'stepper/two'
  post 'stepper/three'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stepper_controller.rb
class StepperController < ApplicationController
  def index
  end

  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stepper_helper.rb
module StepperHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurboRace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= yield :head %>
    <%= turbo_include_tags %>
    <%= stimulus_include_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stepper/index.html.erb
<span class="controller-caption">stimulusJS controller "stepper"</span>
<div data-controller="stepper" class="controller-frame">
  <h1>Turbo Timing Demo</h1>
  <div class="flex">
    <div style="margin: 0 30px 0 30px">
      <p>Turbo's Timing seems to be a bit counter intuitive. I tried to build a stepper using the new turbo-frames (in a way i deemed correct/smart)</p>
      <span>Steps to reproduce - important is what happens (or what doesn't happen) to the output in step 3</span>
      <!-- <ol>
        <li>submit ajax form</li>
        <li>submit turbo form</li>
        <li>step 3 shows ajax output</li>
      </ol>
      <span>- or -</span> -->
      <ol>
        <li>submit turbo form</li>
        <li>submit turbo form</li>
        <li>step 3 is only filled on second submit</li>
      </ol>
    </div>
    <!-- <div class="border-box">
      <p>click these buttons for programmatic submit</p>
      <button data-action="stepper#submitTurboForm">trigger Turbo form via Rails.fire()</button>
      <button data-action="stepper#submitAjaxForm">trigger Ajax form via Rails.fire()</button>
    </div> -->
  </div>

  <h2>Step 1</h2>
  <p>The first form's response will be inserted into turbo-frame "step-two".<br/>This will be done by either using the new turbo-frame feature, or via Ajax submit paired with document.getElementById("step-two").innerHTML = xxx</p>
  <span class="turboframe-caption">turbo-frame step-one</span>
  <turbo-frame id="step-one" src="<%= stepper_one_path %>"></turbo-frame>

  <h2>Step 2</h2>
  <p>Form two is just a few radio-buttons and should submit automatically<br/>It has a stimulus controller attached, which dispatcher a <b>connected</b> event. Somehow the surrounding <b>stepperController</b> will never receive it.</p>
  <span class="turboframe-caption">turbo-frame step-two</span>
  <turbo-frame id="step-two">
    <h2 style="color: red">Initial Content</h2>
  </turbo-frame>

  <h2>Step 3 - The result</h2>
  <span class="turboframe-caption">turbo-frame step-three</span>
  <turbo-frame id="step-three">
    <h2 style="color: red">Initial Content</h2>
  </turbo-frame>

</div>
<hr>
<h2>Other remarks</h2>
<p data-controller="convention-broken">Somehow the naming conventions are broken when using without webpack</p>
<p data-controller="step-two">If I don't use the "step-two" controller in the index page it somehow won't connect in the ajaxed(/turboed) frames</p>

app/views/stepper/one.html.erb
<turbo-frame id="step-one">
  <div class="flex appear-animation">
    <div class="flex-grow">
      <p>This form submits via turbo and uses <b>data-turbo-frame="secondForm"</b></p>
      <span class="form-caption">firstFormTurbo</span>
      <%= form_with url: stepper_two_path, html: { class: "form-frame", "data-turbo-frame" => "step-two", "data-stepper-target" => "firstFormTurbo", "data-action" => "turbo:submit-end->stepper#oneTurboSubmitted ajax:success->stepper#oneTurboSuccess" } do |f| %>
        <%= f.text_field :one, value: "turbo" %>
        <%= f.submit "submit turbo", "data-action" => "turbo:submit-end->stepper#oneTurbo" %>
      <% end %>
      <p class="border-box info hidden">stepperContoller could <span class="hidden" data-stepper-target="turboInfo"><b>NOT</b> </span>see form two, when <b>turbo:submit-end</b> fired<p>
      <p class="border-box warn hidden" data-stepper-target="turboWarning"><b>oneTurboSubmitted</b> submitted secondForm before it was replaced!<br/> Very inconvenient and unexpected behaviour<p>
    </div>

    <!-- <div class="flex-grow">
      <p>This form submits with <b>local: false</b> and <b>data-turbo-frame="_top"</b></p>
      <span class="form-caption">firstFormAjax</span>
      <%= form_with url: stepper_two_path, local: false, html: { class: "form-frame", "data-turbo-frame" => "_top", "data-stepper-target" => "firstFormAjax", "data-action" => "ajax:success->stepper#oneAjaxSuccess turbo:submit-end->stepper#oneAjaxSubmitted" } do |f| %>
        <%= f.text_field :one, value: "ajax" %>
        <%= f.submit "submit ajax" %>
      <% end %>
    </div> -->
  </div>

  <p class="hidden" data-stepper-target="stepTwoInfo" style="">Stepper received <b>connected</b> from stepper-two</span><p>
</turbo-frame>

app/views/stepper/three.html.erb
<turbo-frame id="step-three">
  <div style="padding-left: 40px" class="appear-animation">
    <h1>So, apparently you think <span style="color: red"><%= params[:one]%></span> is <span style="color: red"><%= params[:two] %></span>?</h1>
  </div>
</turbo-frame>

app/views/stepper/two.html.erb
<turbo-frame id="step-two">
  <span class="controller-caption">stimulusJS controller "step-two"</span>
  <div class="controller-frame appear-animation" data-controller="step-two" data-action="connected->stepper#twoConnected connected:delayed->stepper#twoConnectedDelayed">
    <p>hi, I was sent here using <b><%= params[:one] %></b></p>
    <span class="form-caption">secondForm</span>
    <%= form_with url: stepper_three_path, html: { class: "form-frame", "data-turbo-frame" => "step-three", "data-stepper-target" => "secondForm", "data-step-two-target" => "form" } do |f| %>
      <%= f.hidden_field :one, value: params[:one] %>
      <%= f.radio_button :two, "cool", checked: params[:one] == "turbo", "data-action" => "step-two#submit" %>
      <%= f.label :two_cool, 'cool' %>
      <%= f.radio_button :two, "not cool", checked: params[:one] == "ajax", "data-action" => "step-two#submit" %>
      <%= f.label :two_not_cool, 'not cool' %>
    <% end %>
    <p data-stepper-target="twoConnected">Stepper will try to color this blue when receiving <b>connected</b> by step-two<p>
    <p data-stepper-target="twoConnectedDelayed">Stepper will try to color this blue when receiving <b>connected:delayed</b> by step-two<p>
  </div>
</turbo-frame>